# Generated by Django 5.1.15 on 2026-05-12 16:12

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        blank=True, max_length=180, verbose_name="Titre principal"
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(blank=True, verbose_name="Sous-titre"),
                ),
                (
                    "hero_cta_label",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        verbose_name="Libellé du bouton principal",
                    ),
                ),
                (
                    "hero_cta_url",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Lien du bouton principal",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("paragraph", 3),
                            ("image", 7),
                            ("gallery", 9),
                            ("embed", 10),
                            ("document", 14),
                            ("callout", 18),
                            ("cta", 22),
                            ("key_figures", 28),
                            ("accordion", 33),
                            ("table", 38),
                            ("html", 39),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"label": "Texte"}),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("h2", "Titre 2"),
                                        ("h3", "Titre 3"),
                                        ("h4", "Titre 4"),
                                    ],
                                    "label": "Niveau",
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("level", 1)]],
                                {},
                            ),
                            3: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "bold",
                                        "italic",
                                        "ol",
                                        "ul",
                                        "hr",
                                        "link",
                                        "document-link",
                                        "blockquote",
                                    ],
                                    "label": "Paragraphe",
                                },
                            ),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Image"},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Légende", "required": False},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Texte alternatif (accessibilité)",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5), ("alt_text", 6)]],
                                {},
                            ),
                            8: ("wagtail.blocks.ListBlock", (7,), {"label": "Images"}),
                            9: ("wagtail.blocks.StructBlock", [[("images", 8)]], {}),
                            10: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"label": "Média intégré (vidéo, etc.)"},
                            ),
                            11: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"label": "Document"},
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Intitulé affiché", "required": False},
                            ),
                            13: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Description courte", "required": False},
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("document", 11),
                                        ("title", 12),
                                        ("description", 13),
                                    ]
                                ],
                                {},
                            ),
                            15: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("info", "Information"),
                                        ("success", "Réussite"),
                                        ("warning", "Attention"),
                                    ],
                                    "label": "Style",
                                },
                            ),
                            16: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Titre", "required": False},
                            ),
                            17: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "label": "Texte",
                                },
                            ),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [[("style", 15), ("title", 16), ("text", 17)]],
                                {},
                            ),
                            19: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Libellé du bouton"},
                            ),
                            20: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Lien (URL ou /chemin interne)"},
                            ),
                            21: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Principal"),
                                        ("secondary", "Secondaire"),
                                    ],
                                    "label": "Style",
                                },
                            ),
                            22: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 19), ("url", 20), ("style", 21)]],
                                {},
                            ),
                            23: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Valeur (ex. « 13 000 »)"},
                            ),
                            24: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Unité / suffixe (ex. « producteurs »)",
                                    "required": False,
                                },
                            ),
                            25: ("wagtail.blocks.CharBlock", (), {"label": "Libellé"}),
                            26: (
                                "wagtail.blocks.StructBlock",
                                [[("value", 23), ("unit", 24), ("label", 25)]],
                                {},
                            ),
                            27: (
                                "wagtail.blocks.ListBlock",
                                (26,),
                                {"label": "Chiffres clés"},
                            ),
                            28: ("wagtail.blocks.StructBlock", [[("figures", 27)]], {}),
                            29: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Question / Titre"},
                            ),
                            30: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"label": "Réponse / Contenu"},
                            ),
                            31: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 29), ("answer", 30)]],
                                {},
                            ),
                            32: (
                                "wagtail.blocks.ListBlock",
                                (31,),
                                {"label": "Éléments"},
                            ),
                            33: ("wagtail.blocks.StructBlock", [[("items", 32)]], {}),
                            34: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Titre du tableau", "required": False},
                            ),
                            35: ("wagtail.blocks.CharBlock", (), {"label": "Cellule"}),
                            36: ("wagtail.blocks.ListBlock", (35,), {}),
                            37: (
                                "wagtail.blocks.ListBlock",
                                (36,),
                                {"label": "Lignes (la 1re ligne sert d'en-tête)"},
                            ),
                            38: (
                                "wagtail.blocks.StructBlock",
                                [[("caption", 34), ("rows", 37)]],
                                {},
                            ),
                            39: (
                                "wagtail.blocks.RawHTMLBlock",
                                (),
                                {
                                    "label": "Code HTML (à éviter, réservé aux cas particuliers)"
                                },
                            ),
                        },
                        verbose_name="Sections de la page",
                    ),
                ),
                (
                    "show_latest_news",
                    models.BooleanField(
                        default=True, verbose_name="Afficher les dernières actualités"
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page d'accueil",
            },
            bases=("wagtailcore.page",),
        ),
    ]
