# Generated by Django 5.1.15 on 2026-05-12 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hero_cta2_label",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Libellé du bouton secondaire"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_cta2_url",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Lien du bouton secondaire"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_eyebrow",
            field=models.CharField(
                blank=True,
                default="Fonds de Développement des Filières Cacao et Café",
                max_length=80,
                verbose_name="Sur-titre (petit label au-dessus du titre)",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_video_url",
            field=models.URLField(
                blank=True,
                help_text="Vidéo lue en boucle, muette, en arrière-plan du bandeau d'accueil.",
                verbose_name="URL de la vidéo de fond du hero (mp4)",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Image du hero (poster de la vidéo / fond si pas de vidéo)",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_title",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Titre principal"
            ),
        ),
    ]
