# Generated by Django 5.1.15 on 2026-05-12 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_homepage_hero_cta2_label_homepage_hero_cta2_url_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="admin_name",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Nom de l'Administrateur"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="admin_page_url",
            field=models.CharField(
                blank=True,
                default="/le-fodecc/mot-de-l-administrateur",
                max_length=255,
                verbose_name="Lien « Lire le mot complet »",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="admin_photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Photo de l'Administrateur",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="admin_quote",
            field=models.TextField(
                blank=True, verbose_name="Mot de l'Administrateur — citation"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="admin_role",
            field=models.CharField(
                blank=True,
                default="Administrateur / Directeur Général",
                max_length=160,
                verbose_name="Fonction",
            ),
        ),
    ]
