# Generated by Django 5.1.15 on 2026-05-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_admin_name_homepage_admin_page_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="hero_video_url",
            field=models.CharField(
                blank=True,
                help_text="Affichée via un bouton « Voir la vidéo » sur le bandeau d'accueil.",
                max_length=500,
                verbose_name="Vidéo du hero (URL absolue ou chemin local, ex. /video/fodecc.mp4)",
            ),
        ),
    ]
