# Generated by Django 5.1.15 on 2026-05-12 16:12

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Adresse / coordonnées"
                    ),
                ),
                (
                    "legal_text",
                    wagtail.fields.RichTextField(
                        blank=True, verbose_name="Mentions légales (résumé)"
                    ),
                ),
                ("facebook", models.URLField(blank=True, verbose_name="Facebook")),
                ("x_twitter", models.URLField(blank=True, verbose_name="X / Twitter")),
                ("linkedin", models.URLField(blank=True, verbose_name="LinkedIn")),
                ("youtube", models.URLField(blank=True, verbose_name="YouTube")),
            ],
            options={
                "verbose_name": "Pied de page",
            },
        ),
        migrations.CreateModel(
            name="MainMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Menu principal",
                        max_length=100,
                        verbose_name="Nom interne",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu principal",
                "verbose_name_plural": "Menus principaux",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="FODECC", max_length=120, verbose_name="Nom du site"
                    ),
                ),
                (
                    "default_seo_title",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Titre SEO par défaut"
                    ),
                ),
                (
                    "default_seo_description",
                    models.TextField(
                        blank=True, verbose_name="Description SEO par défaut"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email de contact"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Téléphone"
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres du site",
            },
        ),
        migrations.CreateModel(
            name="MainMenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("label", models.CharField(max_length=80, verbose_name="Libellé")),
                (
                    "link_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Lien externe / chemin"
                    ),
                ),
                (
                    "open_in_new_tab",
                    models.BooleanField(
                        default=False, verbose_name="Ouvrir dans un nouvel onglet"
                    ),
                ),
                (
                    "link_page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "menu",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.mainmenu",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Nom")),
                ("url", models.URLField(blank=True, verbose_name="Site web")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ptf", "Partenaire technique et financier"),
                            ("operateur", "Opérateur de filière"),
                            ("institutionnel", "Partenaire institutionnel"),
                        ],
                        default="ptf",
                        max_length=40,
                        verbose_name="Catégorie",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Ordre")),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partenaire",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
